{{- if and .Values.config.signing.secretKey (not .Values.config.signing.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ncps.fullname" . }}-signing-key
  labels:
    {{- include "ncps.labels" . | nindent 4 }}
type: Opaque
data:
  signing-key: {{ .Values.config.signing.secretKey | b64enc | quote }}
{{- end }}
